substitutions:
  name: "pr-02"
  friendly_name: "Pr2"
  project_name: "Nemiah.cosmOS"
  project_version: "1.2.11"
  temperature_offset: "-3"
  humidity_offset: "5"
  temperature_update_interval: "60s"
  illuminance_update_interval: "2s"
  hidden_ssid: "false"
  factory_reset_disabled: "true"
  uart_target_output_disabled: "true"
  uart_presence_output_disabled: "true"
  log_level: "WARN"

packages:
  device_base: !include common/everything-presence-one-base.yaml
  sen0609_base: !include common/sen0609-common.yaml
  co2_base: !include common/modules/co2-rev1.5.yaml
  mqtt: !include common/mqtt.yaml

binary_sensor:
  - platform: gpio
    pin:
      number: 33
      mode: INPUT
    name: PIR
    id: !extend pir_motion_sensor

wifi:
  # Override some wifi params for probe failures; uses same secrets
  fast_connect: false # full scan to find AP if probe is failing
  power_save_mode: NONE
  reboot_timeout: 10min
  enable_rrm: true
  enable_btm: false

sensor:
  - platform: wifi_signal # Reports the WiFi signal strength/RSSI in dB
    name: "WiFi Signal dB"
    id: wifi_signal_db
    update_interval: 10s
    entity_category: "diagnostic"

  - platform: copy # Reports the WiFi signal strength in %
    source_id: wifi_signal_db
    name: "WiFi Signal Percent"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "Signal %"
    entity_category: "diagnostic"
    device_class: ""

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "IP Address"
      icon: "mdi:ip"
    ssid:
      name: "SSID"
      icon: "mdi:wifi"
    bssid:
      name: "BSSID"
      icon: "mdi:access-point"
    mac_address:
      name: "MAC Address"
      icon: "mdi:network"
